@startuml
skinparam actorStyle awesome

' Actor definition
actor User
actor Admin

' Usecase definition
usecase (Register) as uc_register
usecase (Login) as uc_login
usecase (Logout) as uc_logout
usecase (E-mail \nrecover) as uc_email_recover
usecase (Dashboard) as uc_dashboard
usecase (Manage User) as uc_manage_user
usecase (List Users) as uc_list_users
usecase (Edit User) as uc_edit_users
usecase (Delete User) as uc_delete_users
usecase (Select User) as uc_select_user
usecase (Manage Images) as uc_manage_image
usecase (Insert Public \nImage) as uc_public_image
usecase (Insert Private \nImage) as uc_private_image
usecase (List Public \nImages) as uc_list_public_image
usecase (Delete Public \nImage) as uc_delete_public_image
usecase (List Private \nImages) as uc_list_private_image
usecase (Delete Private \nImage) as uc_delete_private_image
usecase (Select Private \nImage) as uc_select_private_image
usecase (Select Public \nImage) as uc_select_public_image
usecase (View Public \nImage) as uc_view_public_image
usecase (View Private \nImage) as uc_view_private_image

Admin --> uc_manage_user
uc_manage_user --> uc_list_users
uc_list_users --> uc_select_user
uc_select_user --> uc_edit_users
uc_select_user --> uc_delete_users

Admin -> uc_manage_image
uc_manage_image -> uc_public_image
uc_manage_image --> uc_private_image
uc_manage_image --> uc_list_public_image
uc_manage_image --> uc_list_private_image
uc_manage_image --> uc_delete_public_image
uc_list_private_image --> uc_select_private_image
uc_select_private_image --> uc_delete_private_image
uc_select_private_image --> uc_view_private_image 
uc_list_public_image --> uc_select_public_image
uc_select_public_image --> uc_view_public_image

User --> uc_login
User --> uc_logout
User --> uc_register
User --> uc_email_recover
User --> uc_dashboard
User --> uc_private_image
User -> uc_public_image
User -> uc_list_private_image
User -> uc_list_public_image

@enduml